# Generated by Django 5.2.6 on 2025-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
