# Generated by Django 5.2.6 on 2025-10-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachments',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
