# Generated by Django 5.2.6 on 2025-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Backlog', max_length=20),
        ),
    ]
